#!/bin/bash

set -e

export HOME=${OPENSHIFT_DATA_DIR}
export LEIN_HOME=${HOME}/lein
export M2_HOME=${HOME}/maven

source "$OPENSHIFT_REPO_DIR/.openshift/lib/node"

ensure_node_is_installed
setup_path_for_custom_node_version

echo "Setting up leiningen"

cd ${HOME}
mkdir -p bin
mkdir -p $LEIN_HOME
mkdir -p $M2_HOME
echo "{:user {:local-repo "'"'$M2_HOME'"'"}}" > $LEIN_HOME/profiles.clj
echo "Home is $HOME, lein-home is $LEIN_HOME"
cat $LEIN_HOME/profiles.clj

wget https://raw.github.com/technomancy/leiningen/stable/bin/lein \
     -O bin/lein

chmod +x bin/lein

cd $OPENSHIFT_REPO_DIR

echo "Installing client-side modules"
npm install bower@1.3.2
./node_modules/bower/bin/bower install

echo "Compiling application"
${HOME}/bin/lein compile :all

exit 0
