#!/bin/bash

set -e

export HOME=${OPENSHIFT_DATA_DIR}

echo "Building application"

cd ${HOME}
echo "Home is $HOME"
mkdir -p bin
mkdir -p ${HOME}/.m2

wget https://raw.github.com/technomancy/leiningen/stable/bin/lein \
     -O bin/lein

chmod +x bin/lein

echo "Compiling application"

cd $OPENSHIFT_REPO_DIR
${HOME}/bin/lein compile :all

return 0
