#!/bin/bash

set -e

export LEIN_HOME="${OPENSHIFT_DIY_DIR}/home"
export M2_REPO="${OPENSHIFT_DIY_DIR}/maven"

export PORT=${OPENSHIFT_DIY_PORT}
export HOST=${OPENSHIFT_DIY_IP}
export HOME=${OPENSHIFT_DATA_DIR}
export DB_HOST=${OPENSHIFT_POSTGRESQL_DB_HOST}
export DB_PORT=${OPENSHIFT_POSTGRESQL_DB_PORT}
export DB_USER=${OPENSHIFT_POSTGRESQL_DB_USERNAME}
export DB_PASSWORD=${OPENSHIFT_POSTGRESQL_DB_USERNAME}
export DATABASE_URL=${OPENSHIFT_POSTGRESQL_DB_URL}
export WEB_AUDIENCE=http://${HOST}:${PORT}

echo "Starting application"
cd ${OPENSHIFT_REPO_DIR}
nohup ${OPENSHIFT_DIY_DIR}/bin/lein with-profile production \
      trampoline run \
      > ${OPENSHIFT_DIY_DIR}/log/server.log 2>&1 &
echo $! > ${OPENSHIFT_DIY_DIR}/app.pid
exit 0
