#!/bin/bash

set -e

export LEIN_HOME="${OPENSHIFT_DIY_DIR}/home"
export M2_REPO="${OPENSHIFT_DIY_DIR}/maven"
PID_FILE="${OPENSHIFT_DIY_DIR}/app.pid"

# Kill process if we have a PID file.
if test -e  $PID_FILE; then
    pid=`cat $PID_FILE`
    kill -0 $pid && kill -15 $pid
fi

# really really bring it all down, but don't worry if nothing was killed
killall -q java 

return 0
